name: 构建并模拟发布

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: 设置 Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 安装构建工具
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: 构建 wheel 包
      run: python -m build

    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: mypkg-wheel
        path: dist/*.whl

    - name: 模拟发布到 PyPI
      run: |
        echo "✅ 构建成功，可以执行 twine upload dist/*"
        echo "（这里为了安全未执行真正上传）"
